version: '3.2'

services:

  signup-db:
    image: signup-db:v1
    networks:
      - app-net
  
  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-app:
    image: signup-app:v2
    depends_on:
      - signup-db
      - message-queue
      - signup-homepage
    networks:
      - app-net
    ports:
      - "80:80"

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net
  
  signup-homepage:
    image: signup-homepage:v1
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat